name: Build and Release

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      # - name: Type check
      #   run: pnpm run typecheck

      - name: Build application
        run: pnpm run build

      - name: Run tests
        run: pnpm run test

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: []
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t scintirete/manager-ui:${GITHUB_REF#refs/tags/} .
          docker build -t scintirete/manager-ui:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images
        run: |
          docker push scintirete/manager-ui:${GITHUB_REF#refs/tags/}
          docker push scintirete/manager-ui:latest

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## 发布说明
            
            ### 新功能
            - 自动构建的 Docker 镜像已推送到 `scintirete/manager-ui:${{ github.ref }}`
            
            ### 使用方法
            ```bash
            docker pull scintirete/manager-ui:${{ github.ref }}
            # 或者使用 latest 标签
            docker pull scintirete/manager-ui:latest
            ```
            
            ### Docker Compose 运行
            ```bash
            docker-compose up -d
            ```
            
            详细的更新内容请查看提交记录。
          draft: false
          prerelease: false 